version: "3.9"

services:
  educational-pg:
    container_name: educational-postgres-container
    image: postgres:alpine
    ports:
      - 8070:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - postgres

  educational-pgadmin:
    container_name: educational-pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8071:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
